### ISSUE TITLE
few tweaks to readme

### ISSUE THREAD

**Issue by amygooch** [SoftwareBrothers/adminjs-example-app#49]
In trying to get this app to run, there are a few things I had to find out the hard way.

the readme says: 

1) To run the demo locally you have to have installed:

* mongodb
* postgresql

or run `docker-compose up`

but this is not quite right, docker-compose up does more than just install those, it runs them and opens the ports.  I'd simplify to just 'run docker-compose up'

2) the readme is missing: 

**yarn build**

3) also after running  yarn start:dev
I think the readme should add something like:

**To test go to http://localhost:3000/admin

login: admin@example.com   
password: password**

(note the login is diff then the demo..)

**Comment by dziraf** [comment]
I updated the README, please have a look if it's more understandable now.
